Use the full workflow script

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -13,12 +13,43 @@ jobs:
     - uses: actions/checkout@v1
     - name: Run the workflow
       run: |
+        set -e
         set -x
+        
+        # Configure Git for the push from the workflow to the repository
+        git config --global user.email "tomas@hubelbauer.net"
+        git config --global user.name "Tomas Hubelbauer"
+
+        # Check out the `master` branch - GitHub Actions checks out detached HEAD
+        git checkout master
+
         # Run the script
         git submodule init
         git submodule update
-        ls -a UZIP.js
         cp UZIP.js/UZIP.js index.js
         echo "export default UZIP;" >> index.js
-        git status
-        git diff
+
+        # Authenticate with GitHub using the out-of-the-box workflow PAT
+        # (The commit using this PAT for authentication won't build GitHub Pages)
+        # (The commit using the custom PAT would built GitHub Pages but also start an infinite GitHub Actions workflow loop)
+        git remote set-url origin https://tomashubelbauer:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
+
+        # Stage the Git index changes (index.js and the submodule) resulting from the CI script
+        git add *
+
+        # Reset unstaged changes so that Git commit won't fail (e.g.: package-lock.json, temporary files, …)
+        git checkout -- .
+        
+        # Bail if there are no changes to commit and hence no GitHub Pages to build
+        if git diff-index --quiet HEAD --; then
+          exit
+        fi
+
+        # Commit the staged changes to the workflow repository
+        git commit -m "Update submodule and UZIP.js ESM"
+        
+        # Rebase if the branch has changed meanwhile or fail on automatically irresolvable conflicts
+        git pull --rebase
+        
+        # Push the commit to the workflow repository 
+        git push
